package com.corejava.Enum;

enum weekDay {

    // Generated by Copilot - start
    SUNDAY(1), MONDAY(2), TUESDAY(3), WEDNESDAY(4), THURSDAY(5), FRIDAY(6), SATURDAY(7);

    private int NumDay;

    private weekDay(int NumDay) {
        this.NumDay = NumDay;
    }
    // Generated by Copilot - end
    // Timestamp: 2026-03-22T17:51:35Z


}

public class EnumClassDemo {

    public static void main(String[] args) {

        weekDay DayEnum = weekDay.FRIDAY;

        int weekNumDay = switch ()
    }

}
