--------------------------------------------------------------------------------
-- Generate portable DDL for FACETS / FACETS_XC tables + indexes + constraints.
--
-- Scope (both schemas: FACETS and FACETS_XC):
--   * Tables whose name STARTS WITH 'CMC_' or 'CDS_'
--   * AND whose name does NOT contain '_ITS_' or '_FSA_'
--
-- What is emitted (to a spooled .sql file you can run on another 19c database):
--   1. CREATE TABLE   (segment/storage/tablespace attributes stripped for portability)
--   2. CREATE INDEX   (non-constraint indexes only, to avoid duplicating PK/UK indexes)
--   3. ALTER TABLE ... ADD CONSTRAINT   for PRIMARY KEY / UNIQUE / CHECK
--   4. ALTER TABLE ... ADD CONSTRAINT   for FOREIGN KEY (emitted LAST so parents exist)
--
-- Tested against: Oracle Database 19c
-- Usage:
--   sqlplus user/pass@db @facets_cmc_cds_ddl.sql
-- Output file: facets_cmc_cds_ddl_out.sql (in the current working directory)
--------------------------------------------------------------------------------

   set echo         off
set verify       off
set feedback     off
set heading      off
set termout      on
set trimspool    on
set trimout      on
set pagesize     0
set linesize     32767
set long         2000000000
set longchunksize 2000000
set serveroutput on size unlimited

-- Make DBMS_METADATA emit clean, portable, runnable DDL.
begin
   dbms_metadata.set_transform_param(
      dbms_metadata.session_transform,
      'PRETTY',
      true
   );
   dbms_metadata.set_transform_param(
      dbms_metadata.session_transform,
      'SQLTERMINATOR',
      true
   );
   dbms_metadata.set_transform_param(
      dbms_metadata.session_transform,
      'SEGMENT_ATTRIBUTES',
      false
   );
   dbms_metadata.set_transform_param(
      dbms_metadata.session_transform,
      'STORAGE',
      false
   );
   dbms_metadata.set_transform_param(
      dbms_metadata.session_transform,
      'TABLESPACE',
      false
   );
   -- Keep constraints OUT of the CREATE TABLE so we can order them safely below.
   dbms_metadata.set_transform_param(
      dbms_metadata.session_transform,
      'CONSTRAINTS',
      false
   );
   dbms_metadata.set_transform_param(
      dbms_metadata.session_transform,
      'REF_CONSTRAINTS',
      false
   );
   dbms_metadata.set_transform_param(
      dbms_metadata.session_transform,
      'CONSTRAINTS_AS_ALTER',
      true
   );
end;
/

spool facets_cmc_cds_ddl_out.sql

pro    --------------------------------------------------------------------------------
prompt -- DDL for FACETS / FACETS_XC  (tables CMC_% or CDS_%, excluding *_ITS_* / *_FSA_*)
pro    -- Generated by facets_cmc_cds_ddl.sql
pro    --------------------------------------------------------------------------------
prompt

pro    --------------------------------------------------------------------------------
prompt -- 1) TABLES
pro    --------------------------------------------------------------------------------
prompt

select dbms_metadata.get_ddl(
   'TABLE',
   t.table_name,
   t.owner
) as ddl
  from dba_tables t
 where t.owner in ( 'FACETS',
                    'FACETS_XC' )
   and ( t.table_name like 'CMC\_%' escape '\'
    or t.table_name like 'CDS\_%' escape '\' )
   and t.table_name not like '%\_ITS\_%' escape '\'
   and t.table_name not like '%\_FSA\_%' escape '\'
 order by t.owner,
          t.table_name;

pro    --------------------------------------------------------------------------------
prompt -- 2) INDEXES (non-constraint indexes only)
pro    --------------------------------------------------------------------------------
prompt

select dbms_metadata.get_ddl(
   'INDEX',
   i.index_name,
   i.owner
) as ddl
  from dba_indexes i
 where i.table_owner in ( 'FACETS',
                          'FACETS_XC' )
   and ( i.table_name like 'CMC\_%' escape '\'
    or i.table_name like 'CDS\_%' escape '\' )
   and i.table_name not like '%\_ITS\_%' escape '\'
   and i.table_name not like '%\_FSA\_%' escape '\'
   and i.index_type not in ( 'LOB' )
   and i.temporary = 'N'
   -- Skip indexes that back PRIMARY KEY / UNIQUE constraints (created with the constraint).
   and not exists (
   select 1
     from dba_constraints c
    where c.owner = i.owner
      and c.index_name = i.index_name
      and c.constraint_type in ( 'P',
                                 'U' )
)
 order by i.owner,
          i.table_name,
          i.index_name;

pro    --------------------------------------------------------------------------------
prompt -- 3) CONSTRAINTS: PRIMARY KEY / UNIQUE / CHECK
pro    --------------------------------------------------------------------------------
prompt

-- Emit PK, UK and CHECK as ALTER TABLE ... ADD CONSTRAINT (one table at a time).
select dbms_metadata.get_dependent_ddl(
   'CONSTRAINT',
   t.table_name,
   t.owner
) as ddl
  from dba_tables t
 where t.owner in ( 'FACETS',
                    'FACETS_XC' )
   and ( t.table_name like 'CMC\_%' escape '\'
    or t.table_name like 'CDS\_%' escape '\' )
   and t.table_name not like '%\_ITS\_%' escape '\'
   and t.table_name not like '%\_FSA\_%' escape '\'
   and exists (
   select 1
     from dba_constraints c
    where c.owner = t.owner
      and c.table_name = t.table_name
      and c.constraint_type in ( 'P',
                                 'U',
                                 'C' )
)
 order by t.owner,
          t.table_name;

pro    --------------------------------------------------------------------------------
prompt -- 4) FOREIGN KEY CONSTRAINTS (emitted last so referenced tables/keys exist)
pro    --------------------------------------------------------------------------------
prompt

select dbms_metadata.get_dependent_ddl(
   'REF_CONSTRAINT',
   t.table_name,
   t.owner
) as ddl
  from dba_tables t
 where t.owner in ( 'FACETS',
                    'FACETS_XC' )
   and ( t.table_name like 'CMC\_%' escape '\'
    or t.table_name like 'CDS\_%' escape '\' )
   and t.table_name not like '%\_ITS\_%' escape '\'
   and t.table_name not like '%\_FSA\_%' escape '\'
   and exists (
   select 1
     from dba_constraints c
    where c.owner = t.owner
      and c.table_name = t.table_name
      and c.constraint_type = 'R'
)
 order by t.owner,
          t.table_name;

pro   
pro    --------------------------------------------------------------------------------
prompt -- End of generated DDL
pro    --------------------------------------------------------------------------------

spool off

set heading      on
set feedback     on
set pagesize     50000